### ISSUE TITLE
reason-tttoe

### ISSUE THREAD

**Issue by venil7** [redex/data#7]
https://github.com/venil7/ReasonML-TicTacToe
```
"reason-tttoe": {
  "category": "library",
  "platforms": ["any"],
  "keywords": ["game development"]
}
```

**Comment by glennsl** [comment]
Hi. There's no indication in the readme that this is actually a library. It's also missing the `repository` and `description` fields in `package.json`, and the `dependencies` aren't properly maintained. `bs-jest` is deprecated and unecessary since you also have `@glennsl/bs-jest`. And `jest` is unnecessary since it comes with `bs-jest`, and also incorrectly listed in `dependencies` instead of `devDependencies`.

Some of the keywords are also much too specific. I think just a single "game development" keyword would be appropriate.

Let me know when you've adressed these, or if you have any questions!

**Comment by venil7** [comment]
@glennsl thanks for your feedback, this has now been addressed

**Comment by glennsl** [comment]
Alrgiht, thanks! I've added it, will publish later
